on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Get pr info
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: pr-info
      - name: Print info
        run: |
          echo "Has PR: ${{ steps.pr-info.outputs.has-pr }}"
          echo "PR: ${{ steps.pr-info.outputs.pr-number }}"
          echo "Contributor name: ${{ steps.pr-info.outputs.contributor-name }}"
          echo "Contributor username: ${{ steps.pr-info.outputs.contributor-username }}"
          echo "Contributor twitter username: ${{ steps.pr-info.outputs.contributor-twitter-username }}"
          echo "Repository name: ${{ steps.pr-info.outputs.repository-name }}"
